import { Standard } from "../../standardsTypes";

export const ANZG_Marine_Water_Toxicant_DGVs_LOSP_99: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
    marine: true,
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 50,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 1000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-38-3",
      chemName: "m-Xylene",
      value: 50,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-70-3",
      chemName: "1,3,5-Trichlorobenzene",
      value: 8,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 110,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-90-7",
      chemName: "Monochlorobenzene",
      value: 15,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 270,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.005,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "118-74-1",
      chemName: "Hexachlorobenzene",
      value: 0.05,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "120-12-7",
      chemName: "Anthracene",
      value: 0.01,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4-Trichlorobenzene",
      value: 20,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "127-18-4",
      chemName: "1,1,2,2-Tetrachloroethylene",
      value: 40,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "142-28-9",
      chemName: "1,3-Dichloropropane",
      value: 700,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "16065-83-1",
      chemName: "Chromium (CrIII)",
      value: 7.7,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (CrVI)",
      value: 0.14,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "206-44-0",
      chemName: "Fluoranthene",
      value: 1,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.0005,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "3383-96-8",
      chemName: "Temephos",
      value: 0.0004,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(alpha)pyrene",
      value: 0.1,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 150,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "60617-06-3",
      chemName: "Corexit 9527",
      value: 230,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "608-93-5",
      chemName: "Pentachlorobenzene",
      value: 1.5,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4-Tetrachlorobenzene",
      value: 2,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "634-90-2",
      chemName: "1,2,3,5-Tetrachlorobenzene",
      value: 3,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 370,
      units: "ug/L",
      comments:
        "Unknown reliability. Recommended for application for slightly to moderately disturbed ecosystems (to protect key species from chronic toxicity). See Technical Brief and Read the detail, below, for details.",
    },
    {
      chemCode: "688-73-3_as_Sn",
      chemName: "Tributyltin",
      value: 0.0004,
      units: "ug Sn/L",
      comments: "High reliability",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 500,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 130,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.004,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 2.2,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 0.1,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 7,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.8,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.7,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "7440-48-4",
      chemName: "Cobalt",
      value: 0.005,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 0.3,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "7440-62-2",
      chemName: "Vanadium",
      value: 50,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 3.3,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "74-90-8",
      chemName: "Cyanide",
      value: 2,
      units: "ug/L",
      comments:
        "Very Low reliability. Cyanide as un-ionised HCN, measured as [CN].",
    },
    {
      chemCode: "75-01-4",
      chemName: "Chloroethylene",
      value: 70,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 3000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethylene",
      value: 500,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "76-01-7",
      chemName: "Pentachloroethane",
      value: 30,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia",
      value: 500,
      units: "ug/L",
      comments:
        "Moderate reliability. Ammonia as total ammonia, measured as [NH3-N] at pH 8.",
    },
    {
      chemCode: "78-87-5",
      chemName: "1,2-Dichloropropane",
      value: 600,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "78-99-9",
      chemName: "1,1-Dichloropropane",
      value: 300,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 140,
      units: "ug/L",
      comments: "Very Low reliability",
    },
    {
      chemCode: "79-01-6",
      chemName: "1,1,2-Trichloroethylene",
      value: 220,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 200,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "80-05-7",
      chemName: "Bisphenol A",
      value: 0.04,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "85-01-8",
      chemName: "Phenanthrene",
      value: 0.6,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 11,
      units: "ug/L",
      comments:
        "To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Refer to Warne et al. (2017) for details.",
    },
    {
      chemCode: "9003-56-9",
      chemName: "Poly(acrylonitrile-co-butadiene-co-styrene)",
      value: 200,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 50,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 50,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-Dichloroaniline",
      value: 85,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "95-94-3",
      chemName: "1,2,4,5-Tetrachlorobenzene",
      value: 3,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "98-82-8",
      chemName: "Cumene (isopropylbenzene)",
      value: 20,
      units: "ug/L",
      comments: "Unknown reliability",
    },
  ],
};
