// July 2023 version

import { Standard } from "../../standardsTypes";

export const ANZG_Freshwater_Toxicant_DGVs_LOSP_80: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
    freshwater: true,
  },
  visual: {
    colour: "#D6EAF8",
    name: "ANZG Freshwater Toxicant DGVs LOSP 80%",
    whiteBar: "ANZG Toxicant DGVs",
    rowB: "80%",
    rowE: "Fresh"
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 160,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "106-42-3",
      chemName: "p-Xylene",
      value: 340,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-Dichlorobenzene",
      value: 100,
      units: "ug/L",
      comments: "Very Low reliability",
    },
    {
      chemCode: "106-48-9",
      chemName: "4-Chlorophenol",
      value: 360,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 4000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 760,
      units: "ug/L",
      comments:
        "Very high reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "108-38-3",
      chemName: "m-Xylene",
      value: 150,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-70-3",
      chemName: "1,3,5-Trichlorobenzene",
      value: 30,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 330,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-90-7",
      chemName: "Monochlorobenzene",
      value: 190,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 1200,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "11097-69-1",
      chemName: "Aroclor 1254",
      value: 0.2,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 1.8,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "118-74-1",
      chemName: "Hexachlorobenzene",
      value: 0.3,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "118-96-7",
      chemName: "2,4,6-Trinitrotoluene",
      value: 210,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "120068-37-3",
      chemName: "Fipronil",
      value: 0.029,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "120-12-7",
      chemName: "Anthracene",
      value: 7,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4-Trichlorobenzene",
      value: 300,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-Dichlorophenol",
      value: 270,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-Dinitrotoluene",
      value: 250,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "121-75-5",
      chemName: "Malathion",
      value: 1.1,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.4,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 35,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "127-18-4",
      chemName: "1,1,2,2-Tetrachloroethylene",
      value: 150,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "131-11-3",
      chemName: "Dimethylphthalate",
      value: 5100,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 3,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief the resources listed in Read the detail, below, for spread of data and its significance.",
    },
    {
      chemCode: "142-28-9",
      chemName: "1,3-Dichloropropane",
      value: 2000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 15,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 9,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief the resources listed in Read the detail, below, for spread of data and its significance.",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 23,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "1746-01-6",
      chemName: "2,3,7,8-Tetrachlorodibenzo-p-dioxin",
      value: 0.08,
      units: "ng/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (CrVI)",
      value: 40,
      units: "ug/L",
      comments:
        "High reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 150,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "206-44-0",
      chemName: "Fluoranthene",
      value: 2,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 57,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "22569-72-8",
      chemName: "Arsenic (AsIII)",
      value: 360,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 8,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 1.2,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 2,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check the resources listed in Read the detail, below, for spread of data and its significance.",
    },
    {
      chemCode: "34014-18-1",
      chemName: "Tebuthiuron",
      value: 160,
      units: "ug/L",
      comments: "Very Low reliability",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.04,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(alpha)pyrene",
      value: 0.7,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "51218-45-2",
      chemName: "Metolachlor",
      value: 15,
      units: "ug/L",
      comments:
        "Very High reliability. The DGVs relate to metolachlor only, and not any of its breakdown products",
    },
    {
      chemCode: "51-28-5",
      chemName: "2,4-Dinitrophenol",
      value: 140,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "53469-21-9",
      chemName: "Aroclor 1242",
      value: 1.7,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3-Dichlorobenzene",
      value: 520,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "554-00-7",
      chemName: "2,4-Dichloroaniline",
      value: 60,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 460,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.04,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.27,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 1,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "58-90-2",
      chemName: "2,3,4,6-Tetrachlorophenol",
      value: 30,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.3,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "608-93-5",
      chemName: "Pentachlorobenzene",
      value: 5,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "62-53-3",
      chemName: "Aniline",
      value: 4800,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4-Tetrachlorobenzene",
      value: 10,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "634-90-2",
      chemName: "1,2,3,5-Tetrachlorobenzene",
      value: 10,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "64-17-5",
      chemName: "Ethanol",
      value: 4000,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "67375-30-8",
      chemName: "a-Cypermethrin",
      value: 0.037,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 1900,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "67-72-1",
      chemName: "Hexachloroethane",
      value: 500,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 2000,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 650,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.06,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "74223-64-6",
      chemName: "Metsulfuron-methyl",
      value: 0.18,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium (pH >6.5)",
      value: 150,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 9.4,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 3600,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 5.4,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 17,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.2,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-38-2 V",
      chemName: "Arsenic (AsV)",
      value: 140,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 2500,
      units: "ug/L",
      comments:
        "Very high reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.8,
      units: "ug/L",
      comments:
        "Very high reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 2.5,
      units: "ug/L",
      comments:
        "Very high reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 31,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "74-90-8",
      chemName: "Cyanide",
      value: 18,
      units: "ug/L",
      comments:
        "Moderate reliability. Cyanide as un-ionised HCN, measured as [CN].",
    },
    {
      chemCode: "75-01-4",
      chemName: "Chloroethylene",
      value: 200,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 7000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethylene",
      value: 1300,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "76-01-7",
      chemName: "Pentachloroethane",
      value: 200,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 0.7,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia",
      value: 2300,
      units: "ug/L",
      comments:
        "High reliability. Ammonia as total ammonia, measured as [NH3-N] at pH 8. DGV may not protect key test species from acute (and chronic) toxicity. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium (total)",
      value: 34,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7782-50-5_Total",
      chemName: "Chlorine",
      value: 13,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulfide",
      value: 2.6,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "78-87-5",
      chemName: "1,2-Dichloropropane",
      value: 1800,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "78-99-9",
      chemName: "1,1-Dichloropropane",
      value: 1000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 8400,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "79-01-6",
      chemName: "1,1,2-Trichloroethylene",
      value: 600,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 900,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "8001-35-2",
      chemName: "Toxaphene",
      value: 0.5,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "80-05-7",
      chemName: "Bishphenol A",
      value: 52,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "8018-01-7",
      chemName: "Mancozeb",
      value: 11,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "84-66-2",
      chemName: "Diethylphthalate",
      value: 1300,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "84-74-2",
      chemName: "Dibutylphthalate",
      value: 65,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 80,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "85-01-8",
      chemName: "Phenanthrene",
      value: 8,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos methyl",
      value: 0.11,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "87-61-6",
      chemName: "1,2,3-Trichlorobenzene",
      value: 30,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 27,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 95,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "9003-56-9",
      chemName: "Poly(acrylonitrile-co-butadiene-co-styrene)",
      value: 1200,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 85,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 85,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 290,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from acute (and chronic) toxicity. Check toxicant DGV technical brief for spread of data and its significance. This DGV is greater than the value for acute toxicity (Warne et al., 2018).",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 830,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "95-47-6",
      chemName: "o-Xylene",
      value: 640,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-Dichlorobenzene",
      value: 270,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-Chlorophenol",
      value: 870,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-Dichloroaniline",
      value: 13,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "95-94-3",
      chemName: "1,2,4,5-Tetrachlorobenzene",
      value: 9,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "98-82-8",
      chemName: "Cumene (isopropylbenzene)",
      value: 70,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 1300,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "AES",
      chemName: "Alcohol ethoxylated sulfate (AES)",
      value: 1100,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "AESurfactant",
      chemName: "Alcohol ethoxylated surfactants (AE)",
      value: 360,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "LAS",
      chemName: "Linear alkylbenzene sulfonates (LAS)",
      value: 1000,
      units: "ug/L",
      comments:
        "Low reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
  ],
};
