import { Standard } from "../../standardsTypes";

export const ANZG_Freshwater_Toxicant_DGVs_LOSP_99: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 50,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "106-42-3",
      chemName: "p-Xylene",
      value: 140,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-Dichlorobenzene",
      value: 40,
      units: "ug/L",
      comments: "Very Low reliability",
    },
    {
      chemCode: "106-48-9",
      chemName: "4-Chlorophenol",
      value: 160,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 1000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 180,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "108-38-3",
      chemName: "m-Xylene",
      value: 50,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-70-3",
      chemName: "1,3,5-Trichlorobenzene",
      value: 8,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 110,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-90-7",
      chemName: "Monochlorobenzene",
      value: 5,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 85,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "11097-69-1",
      chemName: "Aroclor 1254",
      value: 0.01,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.03,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "118-74-1",
      chemName: "Hexachlorobenzene",
      value: 0.05,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "118-96-7",
      chemName: "2,4,6-Trinitrotoluene",
      value: 100,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "120068-37-3",
      chemName: "Fipronil",
      value: 0.013,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "120-12-7",
      chemName: "Anthracene",
      value: 0.01,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4-Trichlorobenzene",
      value: 85,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-Dichlorophenol",
      value: 120,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-Dinitrotoluene",
      value: 16,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "121-75-5",
      chemName: "Malathion",
      value: 0.002,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 0.2,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "127-18-4",
      chemName: "1,1,2,2-Tetrachloroethylene",
      value: 40,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "131-11-3",
      chemName: "Dimethylphthalate",
      value: 3000,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 0.01,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "142-28-9",
      chemName: "1,3-Dichloropropane",
      value: 700,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 0.06,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 2.6,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 0.5,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "1746-01-6",
      chemName: "2,3,7,8-Tetrachlorodibenzo-p-dioxin",
      value: 0.0002,
      units: "ng/L",
      comments:
        "Recommended for adoption for slightly-to-moderately disturbed ecosystems. Value may be below current analytical detection limits.",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (CrVI)",
      value: 0.01,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 0.7,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "206-44-0",
      chemName: "Fluoranthene",
      value: 1,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 0.1,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "22569-72-8",
      chemName: "Arsenic (AsIII)",
      value: 1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.00004,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 0.00003,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "34014-18-1",
      chemName: "Tebuthiuron",
      value: 0.02,
      units: "ug/L",
      comments: "Very Low reliability",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.006,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(alpha)pyrene",
      value: 0.1,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "51218-45-2",
      chemName: "Metolachlor",
      value: 0.0084,
      units: "ug/L",
      comments:
        "Very High reliability. DGV may be below routine analytical limits of reporting. The DGVs relate to metolachlor only, and not any of its breakdown products",
    },
    {
      chemCode: "51-28-5",
      chemName: "2,4-Dinitrophenol",
      value: 13,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "53469-21-9",
      chemName: "Aroclor 1242",
      value: 0.3,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3-Dichlorobenzene",
      value: 160,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "554-00-7",
      chemName: "2,4-Dichloroaniline",
      value: 0.6,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 150,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.0007,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.03,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 0.07,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "58-90-2",
      chemName: "2,3,4,6-Tetrachlorophenol",
      value: 10,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.1,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "608-93-5",
      chemName: "Pentachlorobenzene",
      value: 1.5,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "62-53-3",
      chemName: "Aniline",
      value: 8,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4-Tetrachlorobenzene",
      value: 2,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "634-90-2",
      chemName: "1,2,3,5-Tetrachlorobenzene",
      value: 3,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "64-17-5",
      chemName: "Ethanol",
      value: 400,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "67375-30-8",
      chemName: "a-cypermethrin",
      value: 0.001,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 370,
      units: "ug/L",
      comments:
        "Unknown reliability. Recommended for application for slightly to moderately disturbed ecosystems (to protect key species from chronic toxicity - see Technical Brief for details).",
    },
    {
      chemCode: "67-72-1",
      chemName: "Hexachloroethane",
      value: 290,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 600,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 130,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.01,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "74223-64-6",
      chemName: "Metsulfuron-methyl",
      value: 0.0037,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may be below routine limits of reporting for most commercial laboratories, although some laboratories may be able to achieve lower limits of reporting.",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium (pH >6.5)",
      value: 27,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 1200,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 0.06,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 8,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.02,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-38-2 V",
      chemName: "Arsenic (AsV)",
      value: 0.8,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 340,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.06,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 1,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 2.4,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "74-90-8",
      chemName: "Cyanide",
      value: 4,
      units: "ug/L",
      comments:
        "Moderate reliability. Cyanide as un-ionised HCN, measured as [CN].",
    },
    {
      chemCode: "75-01-4",
      chemName: "Chloroethylene",
      value: 70,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 3000,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethylene",
      value: 500,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "76-01-7",
      chemName: "Pentachloroethane",
      value: 30,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 0.01,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia",
      value: 320,
      units: "ug/L",
      comments:
        "High reliability. Ammonia as total ammonia, measured as [NH3-N] at pH 8.",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium (total)",
      value: 5,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "7782-50-5_Total",
      chemName: "Chlorine",
      value: 0.4,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulfide",
      value: 0.5,
      units: "ug/L",
      comments: "High reliability",
    },
    {
      chemCode: "78-87-5",
      chemName: "1,2-Dichloropropane",
      value: 600,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "78-99-9",
      chemName: "1,1-Dichloropropane",
      value: 300,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 5400,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "79-01-6",
      chemName: "1,1,2-Trichloroethylene",
      value: 220,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 200,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "8001-35-2",
      chemName: "Toxaphene",
      value: 0.1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "80-05-7",
      chemName: "Bisphenol A",
      value: 0.78,
      units: "ug/L",
      comments: "Very high reliability",
    },
    {
      chemCode: "8018-01-7",
      chemName: "Mancozeb",
      value: 0.1,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "84-66-2",
      chemName: "Diethylphthalate",
      value: 900,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "84-74-2",
      chemName: "Dibutylphthalate",
      value: 10,
      units: "ug/L",
      comments:
        "Low reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 0.01,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "85-01-8",
      chemName: "Phenanthrene",
      value: 0.6,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos methyl",
      value: 0.01,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "87-61-6",
      chemName: "1,2,3-Trichlorobenzene",
      value: 3,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 3.6,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 3,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "9003-56-9",
      chemName: "Poly(acrylonitrile-co-butadiene-co-styrene)",
      value: 200,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 2.5,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 2.5,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 3,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 140,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "95-47-6",
      chemName: "o-Xylene",
      value: 200,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-Dichlorobenzene",
      value: 120,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-Chlorophenol",
      value: 340,
      units: "ug/L",
      comments:
        "Moderate reliability. DGV may not protect key test species from chronic toxicity (this refers to experimental chronic values or geometric mean for species). Check toxicant DGV technical brief for spread of data and its significance.",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-Dichloroaniline",
      value: 1.3,
      units: "ug/L",
      comments: "Moderate reliability",
    },
    {
      chemCode: "95-94-3",
      chemName: "1,2,4,5-Tetrachlorobenzene",
      value: 5,
      units: "ug/L",
      comments:
        "Unknown reliability. To account for the bioaccumulating nature of this toxicant, it is recommended that the 99% species protection level DGV is used for slightly to moderately disturbed systems. Also see General comments.",
    },
    {
      chemCode: "98-82-8",
      chemName: "Cumene (isopropylbenzene)",
      value: 20,
      units: "ug/L",
      comments: "Unknown reliability",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 230,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "AES",
      chemName: "Alcohol ethoxylated sulfate (AES)",
      value: 340,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "AESurfactant",
      chemName: "Alcohol ethoxylated surfactants (AE)",
      value: 50,
      units: "ug/L",
      comments: "Low reliability",
    },
    {
      chemCode: "LAS",
      chemName: "Linear alkylbenzene sulfonates (LAS)",
      value: 65,
      units: "ug/L",
      comments: "Low reliability",
    },
  ],
};
