import { Standard } from "../../standardsTypes";

export const NSW_2014_General_Solid_Waste_SCC1_with_leached: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 1080,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (vinyl benzene)",
      value: 108,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "106-44-5",
      chemName: "p-Cresol",
      value: 7200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-Dichlorobenzene",
      value: 270,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "107534-96-3",
      chemName: "Tebuconazole",
      value: 230,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-39-4",
      chemName: "m-Cresol",
      value: 7200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 518,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 3600,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol (non-halogenated)",
      value: 518,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 108,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "117-81-7 & 103-23-1",
      chemName: "Plasticiser compounds",
      value: 600,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-Dinitrotoluene",
      value: 4.68,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloro-ethylene",
      value: 25.2,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1319-77-3",
      chemName: "Cresol (total)",
      value: 7200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylenes (total)",
      value: 1800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1336-36-3",
      chemName: "Polychlorinated biphenyls",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 10000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (VI)",
      value: 1900,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 110,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 7.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "335-67-1",
      chemName: "PFOA",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "355-46-4/1763-23-1",
      chemName: "PFOS +PFHxS",
      value: 1.8,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 10,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 75,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide (total)",
      value: 5900,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "630-20-6",
      chemName: "1,1,1,2-Tetrachloroethane",
      value: 360,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4-Tetrachlorobenzene",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 126,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "69377-81-7",
      chemName: "Fluroxypyr",
      value: 75,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 1080,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 1500,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 1000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 1050,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 180,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 500,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 100,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 100,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-01-4",
      chemName: "Vinyl chloride",
      value: 7.2,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloro-methane",
      value: 310,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloro-ethylene",
      value: 25,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "78-93-3",
      chemName: "Methyl ethyl ketone",
      value: 7200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 43.2,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-01-6",
      chemName: "Trichloro-ethylene",
      value: 18,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 46.8,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 72,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 360,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-48-7",
      chemName: "o-Cresol",
      value: 7200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-Dichlorobenzene",
      value: 155,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-95-4",
      chemName: "2,4,5-Trichlorophenol",
      value: 14400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 72,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "AMENABLE_CYANIDE",
      chemName: "Cyanide (amenable)",
      value: 300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C10-C36",
      chemName: "C10-C36 petroleum hydrocarbons",
      value: 10000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C6-C9",
      chemName: "C6-C9 petroleum hydrocarbons",
      value: 650,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "MOD_PEST_NSW_2014",
      chemName: "Moderately harmful pesticides (total)",
      value: 250,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "SCHD_WSTE_NSW_2014",
      chemName: "Scheduled chemicals",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Polycyclic aromatic hydrocarbons (total)",
      value: 200,
      units: "mg/kg",
      comments: "",
    },
  ],
};
