import { Standard } from "../../standardsTypes";

export const NSW_2014_Excavated_Natural_Material_Max_Average: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
    max_average: true,
  },
  visual: {
    colour: "#CCFFCC",
    name: "NSW 2014 Excavated Natural Material Max Average",
  },
  values: [
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 0.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 30,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 20,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium (total)",
      value: 75,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 100,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 150,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C10-C36",
      chemName: "Total Petroleum Hydrocarbons C10 -C36",
      value: 250,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "EC_Field",
      chemName: "Electrical Conductivity (field)",
      value: 1.5,
      units: "dS/m",
      comments: "",
    },
    {
      chemCode: "EC_Lab",
      chemName: "Electrical Conductivity (lab)",
      value: 1.5,
      units: "dS/m",
      comments: "",
    },
    {
      chemCode: "pH_Field",
      chemName: "pH Field",
      value: { min: 5, max: 9 },
      units: "-",
      comments: "",
    },
    {
      chemCode: "pH_Lab",
      chemName: "pH Lab",
      value: { min: 5, max: 9 },
      units: "-",
      comments: "",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Total PAH",
      value: 20,
      units: "mg/kg",
      comments: "",
    },
  ],
};
