import { Standard } from "../../standardsTypes";

export const NSW_2014_Restricted_Solid_Waste_TCLP2_leached: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: true,
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 120,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (vinyl benzene)",
      value: 12,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-44-5",
      chemName: "p-Cresol",
      value: 800,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4- Dichlorobenzene",
      value: 30,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2- Dichloroethane",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "107534-96-3",
      chemName: "Tebuconazole",
      value: 25.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-39-4",
      chemName: "m-Cresol",
      value: 800,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 57.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 400,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol (non- halogenated)",
      value: 57.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 12,
      units: "mg/L",
      comments:
        "Endosulfan means the total of Endosulfan I, Endosulfan II and Endosulfan sulfate.",
    },
    {
      chemCode: "117-81-7 & 103-23-1",
      chemName: "Plasticiser compounds15",
      value: 4,
      units: "mg/L",
      comments:
        "Plasticiser compounds means the total of di-2-ethyl hexyl phthalate (CAS Registry Number 117-81-7) and di-2-ethyl hexyl adipate (CAS Registry Number 103-23-1) contained within a waste.",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-Dinitrotoluene",
      value: 0.52,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloro-ethylene",
      value: 2.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1319-77-3",
      chemName: "Cresol (total)",
      value: 800,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylenes (total)",
      value: 200,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 600,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (VI)",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 12,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "335-67-1",
      chemName: "PFOA",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "355-46-4/1763-23-1",
      chemName: "PFOS + PFHxS",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 0.16,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide (total)",
      value: 64,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "630-20-6",
      chemName: "1,1,1,2-Tetrachloroethane",
      value: 40,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4- Tetrachlorobenzene",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 24,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "69377-81-7",
      chemName: "Fluroxypyr",
      value: 8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 120,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-01-4",
      chemName: "Vinyl chloride",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 34.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1- Dichloroethylene",
      value: 2.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "78-93-3",
      chemName: "Methyl ethyl ketone",
      value: 800,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 4.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-01-6",
      chemName: "Trichloro-ethylene",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 5.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 40,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-48-7",
      chemName: "o-Cresol",
      value: 800,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2- Dichlorobenzene",
      value: 17.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-95-4",
      chemName: "2,4,5-Trichlorophenol",
      value: 1600,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "AMENABLE_CYANIDE",
      chemName: "Cyanide (amenable)",
      value: 14,
      units: "mg/L",
      comments: "",
    },
  ],
};
