import { Standard } from "../../standardsTypes";

export const NSW_EPA_Recovered_Aggregate_Absolute_Maximum: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  visual: {
    colour: "#FCD5B4",
    name: "NSW EPA Recovered Aggregate Absolute Maximum",
    whiteBar: "NSW EPA - Recovered Aggregate  Order Guidelines (2014)",
    rowB: "RA - Absolute Max Concentration",
  },
  values: [
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 1.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 150,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium (total)",
      value: 120,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 150,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 350,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "EC_Field",
      chemName: "Electrical Conductivity (field)",
      value: 3000,
      units: "uS/cm",
      comments: "",
    },
    {
      chemCode: "Metal",
      chemName: "Metal",
      value: 2,
      units: "%",
      comments: "",
    },
    {
      chemCode: "Plaster",
      chemName: "Plaster",
      value: 0.5,
      units: "%",
      comments: "",
    },
    {
      chemCode: "8007-45-2",
      chemName: "Coal Tar",
      value: 0,
      units: "%",
      comments: "",
    },
  ],
};
