import { Standard } from "../../standardsTypes";

export const NSW_2014_Restricted_Solid_Waste_CT2_No_Leaching: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  visual: {
    colour: "#E4DFEC",
    name: "NSW 2014 Restricted Solid Waste CT2 No Leaching",
    whiteBar: "NSW EPA - Waste Classification Guidelines (2014)",
    rowB: "Restricted Solid Waste (RSW)",
    colourB: "FFFF0000",
    rowE: "CT2",
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 2400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (vinyl benzene)",
      value: 240,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "106-44-5",
      chemName: "p-Cresol",
      value: 16000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-Dichlorobenzene",
      value: 600,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "107534-96-3",
      chemName: "Tebuconazole",
      value: 512,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-39-4",
      chemName: "m-Cresol",
      value: 16000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 1152,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 8000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan5",
      value: 240,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "117-81-7 & 103-23-1",
      chemName: "Plasticiser compounds",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-Dinitrotoluene",
      value: 10.4,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloroethylene",
      value: 56,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1319-77-3",
      chemName: "Cresol (total)",
      value: 16000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylenes (total)",
      value: 4000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1336-36-3",
      chemName: "Polychlorinated biphenyls",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 12000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (VI)",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 240,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 16,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 3.2,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 160,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide (total)",
      value: 1280,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "630-20-6",
      chemName: "1,1,1,2-Tetrachloroethane",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "634-66-2",
      chemName: "1,2,3,4- Tetrachlorobenzene",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "64743-03-9(NonHaloG)",
      chemName: "Phenol (non-halogenated)",
      value: 1152,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "67-66-3",
      chemName: "Chloroform",
      value: 480,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "69377-81-7",
      chemName: "Fluroxypyr",
      value: 160,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: 2400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 16,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 160,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-01-4",
      chemName: "Vinyl chloride",
      value: 16,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 688,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethylene",
      value: 56,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "78-93-3",
      chemName: "Methyl ethyl ketone",
      value: 16000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 96,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-01-6",
      chemName: "Trichloroethylene",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "79-34-5",
      chemName: "1,1,2,2-Tetrachloroethane",
      value: 104,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 160,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-48-7",
      chemName: "o-Cresol",
      value: 16000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-Dichlorobenzene",
      value: 344,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "95-95-4",
      chemName: "2,4,5-Trichlorophenol",
      value: 32000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 160,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "AMENABLE_CYANIDE",
      chemName: "Cyanide (amenable)",
      value: 280,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C10-C36",
      chemName: "C10–C36 petroleum hydrocarbons",
      value: 40000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C6-C9",
      chemName: "C6–C9 petroleum hydrocarbons",
      value: 2600,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "MOD_PEST_NSW_2014",
      chemName: "Moderately harmful pesticides (total)",
      value: 1000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "SCHD_WSTE_NSW_2014",
      chemName: "Scheduled chemicals11",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Polycyclic aromatic hydrocarbons (total)",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
  ],
};
