import { Standard } from "../../standardsTypes";

export const NSW_2014_Excavated_Natural_Material_Absolute_Max: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  visual: {
    colour: "#99FF99",
    name: "NSW 2014 Excavated Natural Material Absolute Max",
    whiteBar: "NSW EPA - Excavated Natural Material Guidelines (2014)",
    rowB: "ENM - Absolute Max concentration"
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethyl-benzene",
      value: 25,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 65,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylene",
      value: 15,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 0.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 100,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 60,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium (total)",
      value: 150,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "C10-C36",
      chemName: "Total Petroleum Hydrocarbons C10 -C36",
      value: 500,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "EC_Field",
      chemName: "Electrical Conductivity (field)",
      value: 3000,
      units: "uS/cm",
      comments: "",
    },
    {
      chemCode: "EC_Lab",
      chemName: "Electrical Conductivity (lab)",
      value: 3000,
      units: "uS/cm",
      comments: "",
    },
    {
      chemCode: "pH_Field",
      chemName: "pH Field",
      value: { min: 4.5, max: 10 },
      units: "-",
      comments: "",
    },
    {
      chemCode: "pH_Lab",
      chemName: "pH Lab",
      value: { min: 4.5, max: 10 },
      units: "-",
      comments: "",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Total PAH",
      value: 40,
      units: "mg/kg",
      comments: "",
    },
  ],
};
