import { Standard } from "../../standardsTypes";

export const ADWG_2022_Aesthetic: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#188E89",
    name: "Australian Drinking Water Guidelines 2022 Aesthetic",
    whiteBar: "Australian Drinking Water Guidelines (ADWG) (2022)",
    rowB: "Aesthetic",
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (vinylbenzene)",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "10049-04-4",
      chemName: "Chlorine dioxide",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-dichlorobenzene",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 0.025,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "12002-48-1",
      chemName: "Trichlorobenzenes (total)",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-dichlorophenol",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylene",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14808-79-8",
      chemName: "Sulfate",
      value: 250,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16887-00-6",
      chemName: "Chloride",
      value: 250,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3-dichlorobenzene",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7429-90-5_Acid_Sol",
      chemName: "Aluminium (acid-soluble)",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-89-6",
      chemName: "Iron",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-23-5",
      chemName: "Sodium",
      value: 180,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7631-86-9",
      chemName: "Silica",
      value: 80,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7664-41-7",
      chemName: "Ammonia (as NH3)",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7782-50-5_Total",
      chemName: "Chlorine",
      value: 0.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulfide",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-trichlorophenol",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-dichlorobenzene",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-chlorophenol",
      value: 0.0001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "Colour",
      chemName: "Colour (true)",
      value: 15,
      units: "HU",
      comments: "",
    },
    {
      chemCode: "DO%Sat",
      chemName: "Dissolved oxygen",
      value: {min: 85, max: 1000},
      units: "%",
      comments: "",
    },
    {
      chemCode: "Hardness_as_CaCO3",
      chemName: "Hardness (as CaCO3)",
      value: 200,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "pH_Lab",
      chemName: "pH",
      value: {
        min: 6.5,
        max: 8.5,
      },
      units: "-",
      comments: "",
    },
    {
      chemCode: "Taste&Odour",
      chemName: "Taste and odour",
      value: -999,
      units: "mg/L",
      comments: "Not offensive to most people",
    },
    {
      chemCode: "TDS",
      chemName: "Total dissolved solids",
      value: 600,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "Temperature",
      chemName: "Temperature",
      value: -999,
      units: "mg/L",
      comments: "No value set",
    },
    {
      chemCode: "TURBIDITY",
      chemName: "Turbidity",
      value: 5,
      units: "NTU",
      comments: "",
    },
  ],
};
