import { Standard } from "../../standardsTypes.js";

export const ADWG_2022_Health: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  values: [
    {
      chemCode: "10028-15-6",
      chemName: "Ozone",
      value: -999,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (vinylbenzene)",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "10049-04-4",
      chemName: "Chlorine dioxide",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "103-23-1",
      chemName: "di(2-ethylhexyl) adipate",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "10599-90-3",
      chemName: "Monochloramine",
      value: 3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "10605-21-7",
      chemName: "Carbendazim",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-dichlorobenzene",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-89-8",
      chemName: "Epichlorohydrin",
      value: 0.0005,
      units: "mg/L",
      comments:
        "The guideline value is below the limit of quantitation. Improved analytical procedures are required for this compound",
    },
    {
      chemCode: "106-93-4",
      chemName: "EDB",
      value: 0.001,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-dichloroethane",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-62-3",
      chemName: "Metaldehyde",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1113-02-6",
      chemName: "Omethoate",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1114-71-2",
      chemName: "Pebulate",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-32-2",
      chemName: "Dicofol",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-90-2",
      chemName: "Fensulfothion",
      value: 0.01,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "116-06-3",
      chemName: "Aldicarb",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "117-81-7",
      chemName: "di(2-ethylhexyl) phthalate",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1194-65-6",
      chemName: "Dichlobenil",
      value: 0.01,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "12002-48-1",
      chemName: "Trichlorobenzenes (total)",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120068-37-3",
      chemName: "Fipronil",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-36-5",
      chemName: "Dichloroprop / Dichlorprop-P",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-dichlorophenol",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "121552-61-2",
      chemName: "Cyprodinil",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "121-75-5",
      chemName: "Maldison (Malathion)",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloroethene",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "128639-02-1",
      chemName: "Carfentrazone-ethyl",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13071-79-9",
      chemName: "Terbufos",
      value: 0.0009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13194-48-4",
      chemName: "Ethoprophos",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "132207-33-1",
      chemName: "Asbestos",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylene",
      value: 0.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "133-06-2",
      chemName: "Captan",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13457-18-6",
      chemName: "Pyrazophos",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "137-42-8",
      chemName: "Metham",
      value: 0.001,
      units: "mg/L",
      comments: "for MTIC:",
    },
    {
      chemCode: "139-13-9",
      chemName: "Nitrilotriacetic acid",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "139-40-2",
      chemName: "Propazine",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "145-73-3",
      chemName: "Endothal",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8",
      chemName: "Nitrate (as nitrate)",
      value: 50,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-65-0",
      chemName: "Nitrite (as nitrite)",
      value: 3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14808-79-8",
      chemName: "Sulfate",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "14866-68-3",
      chemName: "Chlorate",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "1491-41-4",
      chemName: "Naphthalophos",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "14998-27-7",
      chemName: "Chlorite",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "15299-99-7",
      chemName: "Napropamide",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "15541-45-4",
      chemName: "Bromate",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16887-00-6",
      chemName: "Chloride",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "1689-84-5",
      chemName: "Bromoxynil",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 1.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1702-17-6",
      chemName: "Clopyralid",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "17029-22-0",
      chemName: "Hexaflurate",
      value: 0.03,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "17804-35-2",
      chemName: "Benomyl",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (as Cr(VI))",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1897-45-6",
      chemName: "Chlorothalonil",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "19044-88-3",
      chemName: "Oryzalin",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-00-9",
      chemName: "Dicamba",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-16-7",
      chemName: "Propachlor",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1929-77-7",
      chemName: "Vernolate",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1982-47-4",
      chemName: "Chloroxuron",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2032-65-7",
      chemName: "Methiocarb",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "203313-25-1",
      chemName: "Spirotetramat",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "20461-54-5",
      chemName: "Iodide",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "21087-64-9",
      chemName: "Metribuzin",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2164-17-2",
      chemName: "Fluometuron",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "22224-92-6",
      chemName: "Fenamiphos",
      value: 0.0005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "22248-79-9",
      chemName: "Tetrachlorvinphos",
      value: 0.1,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "23103-98-2",
      chemName: "Pirimicarb",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2312-35-8",
      chemName: "Propargite",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23135-22-0",
      chemName: "Oxamyl",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23505-41-1",
      chemName: "Pirimiphos-ethyl",
      value: 0.0005,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "23564-06-9",
      chemName: "Thiophanate",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23950-58-5",
      chemName: "Propyzamide",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "25057-89-0",
      chemName: "Bentazone",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2540-82-1",
      chemName: "Formothion",
      value: 0.05,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "2593-15-9",
      chemName: "Etridiazole",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2631-37-0",
      chemName: "Promecarb",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "27314-13-2",
      chemName: "Norflurazon",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28434-01-7",
      chemName: "Bioresmethrin",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28757-48-4",
      chemName: "Polihexanide",
      value: 0.7,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "29232-93-7",
      chemName: "Pirimiphos methyl",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "298-00-0",
      chemName: "Parathion-methyl",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "298-04-4",
      chemName: "Disulfoton",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "299-84-3",
      chemName: "Fenchlorphos",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "3018-12-0",
      chemName: "dichloroacetonitrile",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "302-17-0",
      chemName: "Chloral hydrate (Trichloroacetaldehyde)",
      value: 0.1,
      units: "mg/L",
      comments: "e",
    },
    {
      chemCode: "30560-19-1",
      chemName: "Acephate",
      value: 0.008,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "309-00-2 + 60-57-1",
      chemName: "Aldrin & Dieldrin",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "314-40-9",
      chemName: "Bromacil",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "3252-43-5",
      chemName: "dibromoacetonitrile",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "330-54-1",
      chemName: "Diuron",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "33089-61-1",
      chemName: "Amitraz",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "330-95-0",
      chemName: "Nicarbazin",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "3337-71-1",
      chemName: "Asulam",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "335-67-1",
      chemName: "PFOA",
      value: 0.56,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "3383-96-8",
      chemName: "Temephos",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "35367-38-5",
      chemName: "Diflubenzuron",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "35400-43-2",
      chemName: "Sulprofos",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "355-46-4/1763-23-1",
      chemName: "Sum of PFOS & PFHxs",
      value: 0.07,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "365400-11-9",
      chemName: "Pyrasulfotole",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "36734-19-7",
      chemName: "Iprodione",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "40487-42-1",
      chemName: "Pendimethalin",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "41198-08-7",
      chemName: "Profenofos",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "422556-08-9",
      chemName: "Pyroxsulam",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "43121-43-3",
      chemName: "Triadimefon",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "4685-14-7",
      chemName: "Paraquat",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "470-90-6",
      chemName: "Chlorfenvinphos",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "4726-14-1",
      chemName: "Nitralin",
      value: -999,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "4824-78-6",
      chemName: "Bromophos-ethyl",
      value: 0.01,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "49866-87-7",
      chemName: "Difenzoquat",
      value: 0.1,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "50-00-0",
      chemName: "Formaldehyde",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "500008-45-7",
      chemName: "Chlorantraniliprole",
      value: 6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo-(a)-pyrene",
      value: 0.00001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "506-77-4",
      chemName: "Cyanogen chloride (as cyanide)",
      value: 0.08,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51-03-6",
      chemName: "Piperonyl butoxide",
      value: 0.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51218-45-2",
      chemName: "Metolachlor/s– Metolachlor",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51235-04-2",
      chemName: "Hexazinone",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51338- 27-3",
      chemName: "Diclofop-methyl",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "513-88-2",
      chemName: "1,1-dichloropropanone",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "51630-58-1",
      chemName: "Fenvalerate",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52315-07-8",
      chemName: "Cypermethrin isomers",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5234-68-4",
      chemName: "Carboxin",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52645-53-1",
      chemName: "Permethrin",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52-68-6",
      chemName: "Trichlorfon",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52756-25-9",
      chemName: "Flamprop-methyl",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52918-63-5",
      chemName: "Deltamethrin",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "534-07-6",
      chemName: "1,3-dichloropropanone",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "540-59-0",
      chemName: "1,2-dichloroethene",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3-dichlorobenzene",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "542-75-6",
      chemName: "1,3-Dichloropropene",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "545-06-2",
      chemName: "trichloroacetonitrile",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "55-38-9",
      chemName: "Fenthion",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "563-12-2",
      chemName: "Ethion",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-35-9",
      chemName: "tributyltin oxide",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide",
      value: 0.08,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5902-51-2",
      chemName: "Terbacil",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5915-41-3",
      chemName: "Terbuthylazine",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "59682-52-9",
      chemName: "Fosamine",
      value: 0.03,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "60-00-4",
      chemName: "Ethylenediamine tetraacetic acid (EDTA)",
      value: 0.25,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60168-88-9",
      chemName: "Fenarimol",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60207-90-1",
      chemName: "Propiconazole",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "61-82-5",
      chemName: "Amitrole",
      value: 0.0009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "62-73-7",
      chemName: "Dichlorvos",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "62-75-9",
      chemName: "N-Nitrosodimethylamine (NDMA)",
      value: 0.0001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "63-25-2",
      chemName: "Carbaryl",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "640-15-3",
      chemName: "Thiometon",
      value: 0.004,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "64902-72-3",
      chemName: "Chlorsulfuron",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "66230-04-4",
      chemName: "Esfenvalerate",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "68359-37-5",
      chemName: "Cyfluthrin,Beta-cyfluthrin",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "69004-03-1",
      chemName: "Toltrazuril",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "6923-22-4",
      chemName: "Monocrotophos",
      value: 0.002,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "69806-40-2",
      chemName: "Haloxyfop",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "709-98-8",
      chemName: "Propanil",
      value: 0.7,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "71-55-6",
      chemName: "1,1,1-Trichloroethane",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "72-43-5",
      chemName: "Methoxychlor",
      value: -999,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "74223-64-6",
      chemName: "Metsulfuron-methyl",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7429-90-5_Acid_Sol",
      chemName: "Aluminium (acid-soluble)",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "7439-89-6",
      chemName: "Iron",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-23-5",
      chemName: "Sodium",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "7440-31-5",
      chemName: "Tin",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "7440-36-0",
      chemName: "Antimony",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-39-3",
      chemName: "Barium",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-61-1",
      chemName: "Uranium",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "74-83-9",
      chemName: "Methyl bromide",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-01-4",
      chemName: "Vinyl chloride",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane (methylene chloride)",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-34-3",
      chemName: "1,1-dichloroethane",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-dichloroethene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7553-56-2",
      chemName: "Iodine",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "756-09-2",
      chemName: "Fluproponate",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-99-0",
      chemName: "2,2-DPA",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "759-94-4",
      chemName: "EPTC",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "76-03-9",
      chemName: "trichloroacetic acid",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "76-06-2",
      chemName: "Chloropicrin",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "7631-86-9",
      chemName: "Silica",
      value: -999,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7664-41-7",
      chemName: "Ammonia (as NH3)",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7782-50-5_Total",
      chemName: "Chlorine",
      value: 5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulfide",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "7786-34-7",
      chemName: "Mevinphos",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "786-19-6",
      chemName: "Carbophenothion",
      value: 0.0005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-01-6",
      chemName: "Trichloroethylene",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "79-06-1",
      chemName: "Acrylamide",
      value: 0.0002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-11-8",
      chemName: "chloroacetic acid",
      value: 0.15,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "79-43-6",
      chemName: "dichloroacetic acid",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "8018-01-7",
      chemName: "Mancozeb",
      value: 0.009,
      units: "mg/L",
      comments: "for ETU:",
    },
    {
      chemCode: "81334-34-1",
      chemName: "Imazapyr",
      value: 9,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "82-68-8",
      chemName: "Quintozene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "834-12-8",
      chemName: "Ametryn",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "83463-62-1",
      chemName: "bromochloroacetonitrile",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos-methyl",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "87-68-3",
      chemName: "Hexachlorobutadiene",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-trichlorophenol",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "886-50-0",
      chemName: "Terbutryn",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "9006-42-2",
      chemName: "Metiram",
      value: 0.009,
      units: "mg/L",
      comments: "for ETU:",
    },
    {
      chemCode: "918-00-3",
      chemName: "1,1,1-trichloropropanone",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "921-03-9",
      chemName: "1,1,3-trichloropropanone",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "93-72-1",
      chemName: "Fenoprop",
      value: 0.01,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 0.1,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "94-74-6",
      chemName: "MCPA",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D [(2,4-Dichlorophenoxy) acetic acid]",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "950-37-8",
      chemName: "Methidathion",
      value: 0.006,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-dichlorobenzene",
      value: 1.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-chlorophenol",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "957-51-7",
      chemName: "Diphenamid",
      value: 0.3,
      units: "mg/L",
      comments:
        "No corresponding fact sheet for these pesticides. Guideline values for these pesticides appeared in a previous version of the ADWG and have been retained in Table 10.5 for information purposes only",
    },
    {
      chemCode: "ChlorFuranones",
      chemName: "Chlorinated furanones (MX)",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "ClosPerf",
      chemName: "Clostridium perfingens",
      value: 0,
      units: "orgs/100mL",
      comments:
        "No guideline value has been set for Clostridium perfringens in drinking water. If used as an indicator and detected in drinking water, immediate action should be taken, including investigation of potential sources of faecal contamination.",
    },
    {
      chemCode: "ColiformThermoTol",
      chemName: "Thermotolerant coliforms",
      value: NaN,
      units: "orgs/100mL",
      comments:
        "Thermotolerant coliforms should not be detected in any 100 mL sample of drinking water. If detected in drinking water, immediate action should be taken including investigation of potential sources of faecal contamination.",
    },
    {
      chemCode: "Colour",
      chemName: "Colour (true)",
      value: -999,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "dialkyltins",
      chemName: "dialkyltins",
      value: -999,
      units: "mg/L",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "DO%Sat",
      chemName: "Dissolved oxygen",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "E.Coli",
      chemName: "Escherichia colii",
      value: NaN,
      units: "orgs/100mL",
      comments:
        "Escherichia coli should not be detected in any 100 mL sample of drinking water. If detected in drinking water, immediate action should be taken including investigation of potential sources of faecal contamination.",
    },
    {
      chemCode: "Gross_alpha_activity",
      chemName: "Gross Alpha Activity",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Gross_beta_activity",
      chemName: "Gross beta activity",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Hardness_as_CaCO3",
      chemName: "Hardness (as CaCO3)",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "Microcystins",
      chemName: "Microcystins",
      value: 1.3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "pH_Lab",
      chemName: "pH",
      value: -999,
      units: "-",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
    {
      chemCode: "Radionuclides",
      chemName: "Radionuclides",
      value: 1,
      units: "mSV",
      comments: "",
    },
    {
      chemCode: "Taste&Odour",
      chemName: "Taste and odour",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "TDS",
      chemName: "Total dissolved solids",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "Temperature",
      chemName: "Temperature",
      value: -999,
      units: "mg/L",
      comments: "Not necessary",
    },
    {
      chemCode: "Trihalomethanes",
      chemName: "Trihalomethanes (THMs) (Total)",
      value: 0.25,
      units: "mg/L",
      comments: "e",
    },
    {
      chemCode: "TURBIDITY",
      chemName: "Turbidity",
      value: -999,
      units: "NTU",
      comments:
        "Insufﬁcient data to set a guideline value based on health considerations",
    },
  ],
};
