import { Standard } from "../../../standardsTypes";

export const NEPM_2013_Table_1A_3_Res_A_B_Soil_HSL_for_Vapour_Intrusion_Sand: Standard =
  {
    standardInfo: {
      matrix: "Soil",
      leached: false,
      sand: true,
      depthDependent: 4,
    },
    visual: {
      colour: "#EBF1DE",
      name: "NEPM 2013 Table 1A-3 Res A & B Soil HSL for Vapour Intrusion - Sand",
      whiteBar: "NEPM (2013) Soil Investigation Levels",
      rowB: "HSL 'A' & 'B'",
      rowC: "SAND",
    },
    values: [
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: 55,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: 160,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: 220,
        units: "mg/kg",
        comments: "",
        conditions: ">=1, <2",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: 310,
        units: "mg/kg",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: 540,
        units: "mg/kg",
        comments: "",
        conditions: ">=4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: 40,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: 60,
        units: "mg/kg",
        comments: "",
        conditions: ">=1, <2",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: 95,
        units: "mg/kg",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: 170,
        units: "mg/kg",
        comments: "",
        conditions: ">=4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 0.5,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 0.5,
        units: "mg/kg",
        comments: "",
        conditions: ">=1, <2",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 0.5,
        units: "mg/kg",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 0.5,
        units: "mg/kg",
        comments: "",
        conditions: ">=4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: 3,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: 3,
        units: "mg/kg",
        comments: "",
        conditions: ">=0, <1",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 45,
        units: "mg/kg",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=0, <1",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 70,
        units: "mg/kg",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=1, <2",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 110,
        units: "mg/kg",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 200,
        units: "mg/kg",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: 110,
        units: "mg/kg",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=0, <1",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: 240,
        units: "mg/kg",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=1, <2",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: 440,
        units: "mg/kg",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
    ],
  };
