import { Standard } from "../../../standardsTypes";

export const NEPM_2013_Table_1A_3_Rec_C_Soil_HSL_for_Vapour_Intrusion_Sand: Standard =
  {
    standardInfo: {
      matrix: "Soil",
      leached: false,
    },
    values: [
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=0, <1",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=1, <2",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/kg",
        comments: "Derived soil HSL exceeds soil saturation concentraiton",
        conditions: ">=4",
      },
    ],
  };
