import { Standard } from "../../standardsTypes";

export const NEPM_2013_Table_1A4_Rec_HSL_C_GW_for_Vapour_Intrusion_Silt: Standard =
  {
    standardInfo: {
      matrix: "Water",
      leached: false,
      silt: true,
    },
    visual: {
      colour: "#F2DCDB",
      name: "NEPM 2013 Table 1A4 Rec HSL C GW for Vapour Intrusion Silt",
    },
    values: [
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
    ],
  };
