import { Standard } from "../../standardsTypes";

export const NEPM_2013_Table_1C_GILs_Fresh_Waters: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#D6DBDF",
    name: "NEPM 2013 Table 1C GILs Fresh Waters",
  },
  values: [
    {
      chemCode: "106-42-3",
      chemName: "p-Xylene",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4- Dichlorobenzene",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "106-48-9",
      chemName: "4-Chlorophenol",
      value: 220,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 370,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 320,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "11097-69-1",
      chemName: "Aroclor 1254",
      value: 0.01,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.03,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4- Trichlorobenzene",
      value: 85,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-Dichlorophenol",
      value: 120,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "121-75-5",
      chemName: "Malathion",
      value: 0.05,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 3.2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "131-11-3",
      chemName: "Dimethylphthalate",
      value: 3700,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylenes",
      value: 550,
      units: "ug/L",
      comments:
        "Sum of individual values for o-xylene (350ug/L) and p-xylene (200ug/L)",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 0.01,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8",
      chemName: "Nitrate (as NO3)",
      value: -999,
      units: "ug/L",
      comments: "refer to guideline",
    },
    {
      chemCode: "14797-65-0",
      chemName: "Nitrite (as NO2)",
      value: -999,
      units: "ug/L",
      comments: "refer to guideline",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 0.06,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 2.6,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 3.5,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium, Cr (VI)",
      value: 1,
      units: "ug/L",
      comments:
        "Figure may not protect key species from chronic toxicity, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 13,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 3.4,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "22569-72-8",
      chemName: "As(III)",
      value: 24,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 2.8,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.01,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 0.01,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "34014-18-1",
      chemName: "Tebuthiuron",
      value: 2.2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.006,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "51-28-5",
      chemName: "2,4-Dinitrophenol",
      value: 45,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "53469-21-9",
      chemName: "Aroclor 1242",
      value: 0.3,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3- Dichlorobenzene",
      value: 260,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "554-00-7",
      chemName: "2,4-Dichloroaniline",
      value: 7,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.004,
      units: "ug/L",
      comments:
        "Figure may not protect key species from chronic toxicity, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide (as un-ionised Cn)",
      value: 7,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.03,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane (γ-HCH)",
      value: 0.2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "58-90-2",
      chemName: "2,3,4,6-Tetrachlorophenol",
      value: 10,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.15,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "62-53-3",
      chemName: "Aniline",
      value: 8,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "64-17-5",
      chemName: "Ethanol",
      value: 1400,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "67-72-1",
      chemName: "Hexachloroethane",
      value: 290,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 950,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.01,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium, Al",
      value: 55,
      units: "ug/L",
      comments: "pH>6.5",
      conditions: "6.5 < pH (Lab) (pH_Units)",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium, Al",
      value: 55,
      units: "ug/L",
      comments: "pH>6.5",
      conditions: "6.5 < pH (Field) (pH_Units)",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 3.4,
      units: "ug/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 1900,
      units: "ug/L",
      comments:
        "Figure may not protect key species from chronic toxicity, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (Total)",
      value: 0.06,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 11,
      units: "ug/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.05,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2 V",
      chemName: "As(V)",
      value: 13,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 370,
      units: "ug/L",
      comments:
        "Figure may not protect key species from chronic toxicity, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.2,
      units: "ug/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 1.4,
      units: "ug/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 8,
      units: "ug/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 0.01,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7664-41-7",
      chemName: "Ammonia (as NH3-N at pH 8)",
      value: 900,
      units: "ug/L",
      comments:
        "For changes in GIL with pH refer to ANZECC & ARMCANZ (2000). Figure may not protect key species from chronic toxicity, refer ANZECC & ARMCANZ",
    },
    {
      chemCode: "7723-14-0",
      chemName: "Phosphorus",
      value: -999,
      units: "ug/L",
      comments: "refer to guideline",
    },
    {
      chemCode: "7727-37-9",
      chemName: "Nitrogen",
      value: -999,
      units: "ug/L",
      comments: "refer to guideline",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium (Total)",
      value: 5,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulphide (un-ionised H2Smeasured as S)",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-Trichloroethane",
      value: 6500,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "8001-35-2",
      chemName: "Toxafene",
      value: 0.1,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "84-66-2",
      chemName: "Diethylphthalate",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "84-74-2",
      chemName: "Dibutylphthalate",
      value: 10,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 1.4,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "87-61-6",
      chemName: "1,2,3- Trichlorobenzene",
      value: 3,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 3.6,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 3,
      units: "ug/L",
      comments:
        "Chemical for which possible bioaccumulation and secondary poisoning effects should be considered, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 16,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 16,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 36,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D [2,4-dichlorophenoxy acetic acid]",
      value: 280,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "95-47-6",
      chemName: "o-Xylene",
      value: 350,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2- Dichlorobenzene",
      value: 160,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-Chlorophenol",
      value: 340,
      units: "ug/L",
      comments:
        "Figure may not protect key species from chronic toxicity, refer to ANZECC & ARMCANZ (2000) for further guidance.",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-Dichloroaniline",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "AES",
      chemName: "Alcohol ethoxylated sulfate (AES)",
      value: 650,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "AESurfactant",
      chemName: "Alcohol ethoxylated surfactants (AE)",
      value: 140,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "LAS",
      chemName: "Linear alkylbenzene sulfonates (LAS)",
      value: 280,
      units: "ug/L",
      comments: "",
    },
  ],
};
