import { Standard } from "../../standardsTypes";

export const NEPM_2013_Table_1C_GILs_Drinking_Water: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#46a5a1",
    name: "NEPM 2013 Table 1C GILs Drinking Water",
    whiteBar: "NEPM 2013 Water",
    rowB: "NEPM 2013 GILs Drinking Water",
  },
  values: [
    {
      chemCode: "100-41-4",
      chemName: "Ethylbenzene",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "100-42-5",
      chemName: "Styrene (Vinyl benzene)",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1024-57-3",
      chemName: "Heptachlor epoxide",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "10599-90-3",
      chemName: "Monochloramine",
      value: 3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "10605-21-7",
      chemName: "Carbendazim (Thiophanate-methyl)",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4- Dichlorobenzene",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "106-89-8",
      chemName: "Epichlorohydrin",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-62-3",
      chemName: "Metaldehyde",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-70-3",
      chemName: "1,3,5-Trichlorobenzene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-88-3",
      chemName: "Toluene",
      value: 0.8,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "108-90-7",
      chemName: "Chlorobenzene",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1113-02-6",
      chemName: "Omethoate",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1114-71-2",
      chemName: "Pebulate",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "115-32-2",
      chemName: "Dicofol",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "116-06-3",
      chemName: "Aldicarb",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "117-81-7",
      chemName: "Di(2-ethylhexyl) phthalate",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "12002-48-1",
      chemName: "total trichlorobenzenes",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120068-37-3",
      chemName: "Fipronil",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-36-5",
      chemName: "Dichloroprop",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4- Trichlorobenzene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-Dichlorophenol",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "121552-61-2",
      chemName: "Cyprodinil",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "121-75-5",
      chemName: "Malathion",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloroethene (PCE) (Perchloroethene)",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "128639-02-1",
      chemName: "Carfentrazone-ethyl",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13071-79-9",
      chemName: "Terbufos",
      value: 0.0009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13194-48-4",
      chemName: "Ethoprophos",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1330-20-7",
      chemName: "Xylenes",
      value: 0.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "133-06-2",
      chemName: "Captan",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "13457-18-6",
      chemName: "Pyrazophos",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "137-42-8",
      chemName: "Metham (as methylisothiocyanate, MITC)",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "139-13-9",
      chemName: "Nitrilotriacetic acid",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "139-40-2",
      chemName: "Proparzine",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "145-73-3",
      chemName: "Endothal",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8",
      chemName: "Nitrate (as NO3)",
      value: 50,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-65-0",
      chemName: "Nitrite (as NO2)",
      value: 3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14808-79-8",
      chemName: "Sulphate (as SO4)",
      value: 500,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "15299-99-7",
      chemName: "Napropamide",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "15541-45-4",
      chemName: "Bromate",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1689-84-5",
      chemName: "Bromoxynil",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 1.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1702-17-6",
      chemName: "Clopyralid",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "17804-35-2",
      chemName: "Benomyl",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium, Cr (VI)",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1897-45-6",
      chemName: "Chlorothalonil",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "19044-88-3",
      chemName: "Oryzalin",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-00-9",
      chemName: "Dicamba",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1918-16-7",
      chemName: "Propachlor",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "1929-77-7",
      chemName: "Vernolate",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2032-65-7",
      chemName: "Methiocarb",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "203313-25-1",
      chemName: "Spirotetramat",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "20461-54-5",
      chemName: "Iodide",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "21087-64-9",
      chemName: "Metribuzin",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2164-17-2",
      chemName: "Fluometuron",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "22224-92-6",
      chemName: "Fenamiphos",
      value: 0.0005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23103-98-2",
      chemName: "Pirimicarb",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2312-35-8",
      chemName: "Propargite",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23135-22-0",
      chemName: "Oxamyl",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "23950-58-5",
      chemName: "Propyzamide",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "25057-89-0",
      chemName: "Bentazone",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2593-15-9",
      chemName: "Etridiazole",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "27314-13-2",
      chemName: "Norflurazon",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28434-01-7",
      chemName: "Bioresmethrin",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "28757-48-4",
      chemName: "Polihexanide",
      value: 0.7,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "29232-93-7",
      chemName: "Pirimiphos methyl",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "298-00-0",
      chemName: "Parathion methyl",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "298-04-4",
      chemName: "Disulfoton",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "30560-19-1",
      chemName: "Acephate",
      value: 0.008,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "309-00-2 + 60-57-1",
      chemName: "Aldrin plus Dieldrin",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "309-00-2 + 60-57-1",
      chemName: "Dieldrin plus Aldrin",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "314-40-9",
      chemName: "Bromacil",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "330-54-1",
      chemName: "Diuron",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "33089-61-1",
      chemName: "Amitraz",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "330-95-0",
      chemName: "Nicarbazin",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "3337-71-1",
      chemName: "Asulam",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "3383-96-8",
      chemName: "Temephos",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "35367-38-5",
      chemName: "Diflubenzuron",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "35400-43-2",
      chemName: "Sulprofos",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "365400-11-9",
      chemName: "Pyrasulfatole",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "36734-19-7",
      chemName: "Iprodione",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "40487-42-1",
      chemName: "Pendimethalin",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "41198-08-7",
      chemName: "Profenofos",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "422556-08-9",
      chemName: "Pyroxsulam",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "43121-43-3",
      chemName: "Triadimefon",
      value: 0.09,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "4685-14-7",
      chemName: "Paraquat",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "470-90-6",
      chemName: "Chlorfenvinphos",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-00-0",
      chemName: "Formaldehyde",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "500008-45-7",
      chemName: "Chlorantraniliprole",
      value: 6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo[a]pyrene",
      value: 0.00001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51-03-6",
      chemName: "Piperonyl butoxide",
      value: 0.6,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51218-45-2",
      chemName: "Metolachlor/s–Metolachlor",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51235-04-2",
      chemName: "Hexazinone",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51338- 27-3",
      chemName: "Diclofop-methyl",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "51630-58-1",
      chemName: "Fenvalerate",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52315-07-8",
      chemName: "Cypermethrin isomers",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5234-68-4",
      chemName: "Carboxin",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52645-53-1",
      chemName: "Permethrin",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52-68-6",
      chemName: "Trichlorfon",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52756-25-9",
      chemName: "Flamprop-methyl",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "52918-63-5",
      chemName: "Deltramethrin",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "540-59-0",
      chemName: "1,2-Dichoroethene",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "542-75-6",
      chemName: "1,3-Dichloropropene",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "55-38-9",
      chemName: "Fenthion",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Tetrachloromethane (carbon tetrachloride)",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "563-12-2",
      chemName: "Ethion",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-35-9",
      chemName: "Tributyl tin oxide",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide (as un-ionised Cn)",
      value: 0.08,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane (γ-HCH)",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5902-51-2",
      chemName: "Terbacil",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "5915-41-3",
      chemName: "Terbuthylazine",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60-00-4",
      chemName: "Ethylenediamine tetra-acetic acid (EDTA)",
      value: 0.25,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60168-88-9",
      chemName: "Fenarimol",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60207-90-1",
      chemName: "Propiconazole",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "61-82-5",
      chemName: "Amitrole",
      value: 0.0009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "62-73-7",
      chemName: "Dichlorvos",
      value: 0.005,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "63-25-2",
      chemName: "Carbaryl",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "640-15-3",
      chemName: "Thiometon",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "64902-72-3",
      chemName: "Chlorsulfuron",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "66230-04-4",
      chemName: "Esfenvalerate",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "68359-37-5",
      chemName: "Cyfluthrin, Beta-cyfluthrin",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "69004-03-1",
      chemName: "Toltrazuril",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "69806-40-2",
      chemName: "Haloxyfop",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "709-98-8",
      chemName: "Propanil",
      value: 0.7,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "74223-64-6",
      chemName: "Metsulfuron-methyl",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 0.01,
      units: "mg/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (Total)",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 0.05,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 0.02,
      units: "mg/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-36-0",
      chemName: "Antimony",
      value: 0.003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-39-3",
      chemName: "Barium",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 0.06,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.002,
      units: "mg/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 2,
      units: "mg/L",
      comments:
        "Values calculated using hardness of 30 mg/L CaCO3. Refer ANZECC & ARMCANZ (2000) for site specific hardness guidance",
    },
    {
      chemCode: "7440-61-1",
      chemName: "Uranium",
      value: 0.017,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "74-83-9",
      chemName: "Methyl bromide",
      value: 0.001,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-01-4",
      chemName: "Chloroethene (vinyl chloride)",
      value: 0.0003,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-09-2",
      chemName: "Dichloromethane",
      value: 0.004,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "756-09-2",
      chemName: "Fluproponate",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "75-99-0",
      chemName: "2,2-DPA",
      value: 0.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "759-94-4",
      chemName: "EPTC",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium (Total)",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7786-34-7",
      chemName: "Mevinphos",
      value: 0.006,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "8018-01-7",
      chemName: "Mancozeb (as ETU, ethylene thiourea)",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "81334-34-1",
      chemName: "Imazapyr",
      value: 9,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "82-68-8",
      chemName: "Quintozene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "834-12-8",
      chemName: "Ametryn",
      value: 0.07,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 0.007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos-methyl",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "87-61-6",
      chemName: "1,2,3- Trichlorobenzene",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "87-68-3",
      chemName: "Hexachlorobutadiene",
      value: 0.0007,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "886-50-0",
      chemName: "Terbutryn",
      value: 0.4,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "9006-42-2",
      chemName: "Metiram (as ETU, ethylene thiourea)",
      value: 0.009,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "94-74-6",
      chemName: "MCPA",
      value: 0.04,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D [2,4-dichlorophenoxy acetic acid]",
      value: 0.03,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "950-37-8",
      chemName: "Methidathion",
      value: 0.006,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2- Dichlorobenzene",
      value: 1.5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-Chlorophenol",
      value: 0.3,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "Trihalomethanes",
      chemName: "Trihalomethanes (total)",
      value: 0.25,
      units: "mg/L",
      comments: "",
    },
  ],
};
