import { Standard } from "../../standardsTypes";

export const NEPM_2013_Table_1A4_Res_HSL_A_B_GW_for_Vapour_Intrusion_Silt: Standard =
  {
    standardInfo: {
      matrix: "Water",
      leached: false,
      silt: true,
      depthDependent: ["2-4m", "4-8m", ">8m"],
    },
    visual: {
      colour: "#EBF1DE",
      name: "NEPM 2013 Table 1A4 Res HSL A-B GW for Vapour Intrusion Silt",
      whiteBar: "NEPM 2013 Water",
      rowB: "NEPM 2013 Table 1A4 Res HSL A-B GW for Vapour Intrusion Silt",
    },
    values: [
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "100-41-4",
        chemName: "Ethylbenzene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "108-88-3",
        chemName: "Toluene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "1330-20-7",
        chemName: "Xylenes",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 4,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 5,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "71-43-2",
        chemName: "Benzene",
        value: 5,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "91-20-3",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=2, <4",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=4, <8",
      },
      {
        chemCode: "91-20-3_VOC",
        chemName: "Naphthalene",
        value: -999,
        units: "mg/L",
        comments: "",
        conditions: ">=8",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 6,
        units: "mg/L",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 6,
        units: "mg/L",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=4, <8",
      },
      {
        chemCode: "F1-BTEX",
        chemName: "F1",
        value: 6,
        units: "mg/L",
        comments:
          "To obtain F1 subtract the sum of BTEX concentrations from the C6 - C10 fraction.",
        conditions: ">=8",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=2, <4",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=4, <8",
      },
      {
        chemCode: "F2-NAPHTHALENE",
        chemName: "F2",
        value: -999,
        units: "mg/L",
        comments:
          "To obtain F2 subtract napthalene from the >C10 - C16 fraction.",
        conditions: ">=8",
      },
    ],
  };
