import { Standard } from "../../../standardsTypes";

export const NEPM_2013_Table_1A_1_HILs_Rec_C_Soil: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  visual: {
    colour: "#F2DCDB",
    name: "NEPM 2013 Table 1A-1 HILs Rec C Soil",
  },
  values: [
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 40000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 340,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "118-74-1",
      chemName: "HCB",
      value: 10,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1319-77-3",
      chemName: "Cresols",
      value: 4000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1336-36-3",
      chemName: "PCBs",
      value: 1,
      units: "mg/kg",
      comments:
        "PCBs: HIL refers to non-dioxin like PCBs only. Where PCB source is known, or suspected at a site, a site-specific assessment of exposure to all PCBs (inc dioxin like PCBs) should be undertaken",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (VI)",
      value: 300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 5700,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "22967-92-6",
      chemName: "Methyl mercury",
      value: 13,
      units: "mg/kg",
      comments:
        "Methyl Hg: assess only where evidence of any potential source. Maybe assoc. with inorg. Hg & anaerobic microorg. activity in aquatic environments. Consider reliability/quality of sampling/analysis.",
    },
    {
      chemCode: "2385-85-5",
      chemName: "Mirex",
      value: 20,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 250,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "309-00-2 + 60-57-1",
      chemName: "Aldrin and dieldrin",
      value: 10,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 70,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 20,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "72-43-5",
      chemName: "Methoxychlor",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 600,
      units: "mg/kg",
      comments:
        "Lead: HILs A,B,C based on blood lead models (IEUBK & HIL D on adult lead model for where 50% bioavailability considered. Site-specific bioavailability should be considered where appropriate.",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 19000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 80,
      units: "mg/kg",
      comments:
        "Elemental mercury: HIL does not address elemental mercury. a site specific assessment should be considered if elemental mercury is present, or suspected to be present.",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 1200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 300,
      units: "mg/kg",
      comments:
        "Arsenic: HIL assumes 70% oral bioavailability. Site-specific bioavailability maybe important and should be considered where appropriate (refer Shedule B7).",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 90,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 20000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 90,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-48-4",
      chemName: "Cobalt",
      value: 300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 17000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 30000,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 10,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 700,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "8001-35-2",
      chemName: "Toxaphene",
      value: 30,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "82657-04-3",
      chemName: "Bifenthrin",
      value: 730,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 120,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "93-65-2",
      chemName: "Mecoprop",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "94-74-6",
      chemName: "MCPA",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 1300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "94-81-5",
      chemName: "MCPB",
      value: 800,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "BaP_TEQ_0.5xEQL",
      chemName: "Carcinogenic PAHs (as BaP TEQ)",
      value: 3,
      units: "mg/kg",
      comments:
        "Carcinogenic PAHs: HIL based on 8 carc. PAHs & their TEFs (rel to BaP ref Schedule 7) BaP TEQ calc by multiplying the conc of each carc. PAH in sample by its BaP TEF (ref Table 1A(1)) & summing",
    },
    {
      chemCode: "BaP_TEQ_0xEQL",
      chemName: "Carcinogenic PAHs (as BaP TEQ)",
      value: 3,
      units: "mg/kg",
      comments:
        "Carcinogenic PAHs: HIL based on 8 carc. PAHs & their TEFs (rel to BaP ref Schedule 7) BaP TEQ calc by multiplying the conc of each carc. PAH in sample by its BaP TEF (ref Table 1A(1)) & summing",
    },
    {
      chemCode: "BaP_TEQ_1.0xEQL",
      chemName: "Carcinogenic PAHs (as BaP TEQ)",
      value: 3,
      units: "mg/kg",
      comments:
        "Carcinogenic PAHs: HIL based on 8 carc. PAHs & their TEFs (rel to BaP ref Schedule 7) BaP TEQ calc by multiplying the conc of each carc. PAH in sample by its BaP TEF (ref Table 1A(1)) & summing",
    },
    {
      chemCode: "BaP_WHOTEQ",
      chemName: "Carcinogenic PAHs (as BaP TEQ)",
      value: 3,
      units: "mg/kg",
      comments:
        "Carcinogenic PAHs: HIL based on 8 carc. PAHs & their TEFs (rel to BaP ref Schedule 7) BaP TEQ calc by multiplying the conc of each carc. PAH in sample by its BaP TEF (ref Table 1A(1)) & summing",
    },
    {
      chemCode: "CPAHs as B(a)P TPE",
      chemName: "Carcinogenic PAHs (as BaP TEQ)",
      value: 3,
      units: "mg/kg",
      comments:
        "Carcinogenic PAHs: HIL based on 8 carc. PAHs & their TEFs (rel to BaP ref Schedule 7) BaP TEQ calc by multiplying the conc of each carc. PAH in sample by its BaP TEF (ref Table 1A(1)) & summing",
    },
    {
      chemCode: "DDT+DDE+DDD",
      chemName: "DDT+DDE+DDD",
      value: 400,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "EPAVic_PAHs",
      chemName: "Total PAHs",
      value: 300,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "FREE_CYANIDE",
      chemName: "Cyanide (free)",
      value: 240,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Total PAHs",
      value: 300,
      units: "mg/kg",
      comments:
        "Total PAHs: Based on sum of 16 most common reported (WHO 98). HIL application should consider presence of carcinogenic PAHs (should meet BaP TEQ HIL) & napthalene (should meet relevant HSL)",
    },
  ],
};
