import { Standard } from "../../standardsTypes";

export const ANZECC_2000_Irrigation_Short_Term_Trigger_Values: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#FF9B9B",
    name: "ANZECC 2000 Irrigation Short Term Trigger Values",
  },
  values: [
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 2,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium",
      value: 20,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7439-89-6",
      chemName: "Iron",
      value: 10,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 5,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7439-93-2",
      chemName: "Lithium",
      value: 2.5,
      units: "mg/l",
      comments: "(0.075 Citrus crops)",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 10,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.002,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 0.05,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 2,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 2,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-41-7",
      chemName: "Beryllium",
      value: 0.5,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.05,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium",
      value: 1,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-48-4",
      chemName: "Cobalt",
      value: 0.1,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 5,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-61-1",
      chemName: "Uranium",
      value: 0.1,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-62-2",
      chemName: "Vanadium",
      value: 0.5,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 5,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "7723-14-0",
      chemName: "Phosphorus",
      value: -999,
      units: "mg/L",
      comments: "Requires site-specific assessment",
    },
    {
      chemCode: "7727-37-9",
      chemName: "Nitrogen",
      value: -999,
      units: "mg/L",
      comments: "Requires site-specific assessment",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 0.05,
      units: "mg/l",
      comments: "",
    },
    {
      chemCode: "Gross_alpha_activity",
      chemName: "Gross alpha",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Gross_beta_activity",
      chemName: "gross beta (excluding k-40)",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Radium-226",
      chemName: "Radium 226",
      value: 5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Radium-228",
      chemName: "Radium 228",
      value: 2,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Uranium-238",
      chemName: "Uranium 238",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
  ],
};
