import { Standard } from "../../standardsTypes";

export const ANZECC_2000_Livestock_DW_Low_Risk_Trigger_Values: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#FF9393",
    name: "ANZECC 2000 Livestock Drinking Water Low Risk Trigger Values",
    whiteBar: "ANZECC 2000 Water Quality Guidelines",
    rowB: "Livestock Drinking Water Low Risk Trigger Values",
  },
  values: [
    {
      chemCode: "101043-37-2",
      chemName: "microcystin-LR",
      value: 2.3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8",
      chemName: "Nitrate",
      value: 400,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8(as N)",
      chemName: "Nitrate-N",
      value: 90,
      units: "mg/L",
      comments: "1 mg/L nitrate-N = 4.43 mg/L nitrate",
    },
    {
      chemCode: "14797-65-0",
      chemName: "Nitrite",
      value: 30,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "14797-65-0(as N)",
      chemName: "Nitrite-N",
      value: 9,
      units: "mg/L",
      comments: "1 mg/L nitrite-N = 3.29 mg/L nitrite",
    },
    {
      chemCode: "14808-79-8",
      chemName: "Sulfate",
      value: 1000,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "16984-48-8",
      chemName: "Fluoride",
      value: 2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium",
      value: 5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 0.1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.002,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7439-98-7",
      chemName: "Molybdenum",
      value: 0.15,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 0.5,
      units: "mg/L",
      comments:
        "Up to 5 mg/L may be tolerated if not provided as food additive and natural diet levels are low",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 5,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.01,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-48-4",
      chemName: "Cobalt",
      value: 1,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 0.4,
      units: "mg/L",
      comments: "(sheep value, cattle = 1, pigs = 5, poultry = 5)",
    },
    {
      chemCode: "7440-61-1",
      chemName: "Uranium",
      value: 0.2,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 20,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7440-70-2",
      chemName: "Calcium",
      value: 1000,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 0.02,
      units: "mg/L",
      comments: "",
    },
    {
      chemCode: "ColiformThermoTol",
      chemName: "thermotolerant coliforms",
      value: 100,
      units: "cfu/100mL",
      comments: "",
    },
    {
      chemCode: "Gross_alpha_activity",
      chemName: "Gross alpha",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Grossbetaactivity-40",
      chemName: "Gross beta (excluding K-40)",
      value: 0.5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Microcystis",
      chemName: "Microcystis",
      value: 11500,
      units: "cells/mL",
      comments: "",
    },
    {
      chemCode: "Radium-226",
      chemName: "Radium 226",
      value: 5,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Radium-228",
      chemName: "Radium 228",
      value: 2,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "TDS",
      chemName: "Total dissolved solids (salinity)",
      value: 2000,
      units: "mg/L",
      comments:
        "(poultry value, pigs/horses = 4000, sheep = 5000, dairy cattle = 2500, beef cattle = 4000",
    },
    {
      chemCode: "Uranium-238",
      chemName: "Uranium 238",
      value: 0.2,
      units: "Bq/L",
      comments: "",
    },
  ],
};
