import { Standard } from "../../standardsTypes";

export const ANZECC_2000_MW_90: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
    marine: true,
  },
  visual: {
    colour: "#AED6F1",
    name: "ANZECC 2000 Marine Water 90%",
    whiteBar: "ANZECC 2000 Water Quality Guidelines",
    rowE: "Marine",
    rowB: "90%",
  },
  values: [
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 520,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.02,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4-trichlorobenzene",
      value: 140,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "16065-83-1",
      chemName: "Chromium (Cr III)",
      value: 48.6,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (CrVI)",
      value: 20,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.04,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "3383-96-8",
      chemName: "Temephos",
      value: 0.4,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide",
      value: 7,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "60617-06-3",
      chemName: "Corexit 9527",
      value: 2200,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "688-73-3_as_Sn",
      chemName: "Tributyltin (as Sn)",
      value: 0.02,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 900,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 6.6,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 0.7,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 200,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 1.8,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 14,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-48-4",
      chemName: "Cobalt",
      value: 14,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-62-2",
      chemName: "Vanadium",
      value: 160,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 23,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7664-41-7",
      chemName: "Ammonia",
      value: 1200,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia as N",
      value: 1200,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-trichloroethane",
      value: 5800,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 33,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "9003-56-9",
      chemName: "Poly(acrylonitrile-co-butadiene-co-styrene)",
      value: 280,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 90,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 90,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-dichloroaniline",
      value: 190,
      units: "ug/l",
      comments: "",
    },
  ],
};
