import { Standard } from "../../standardsTypes";

export const ANZECC_2000_Recreational_water_quality_and_aesthetics: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  values: [
    {
      chemCode: "101-27-9",
      chemName: "Barban",
      value: 300,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "10605-21-7",
      chemName: "Carbendazim",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "107-06-2",
      chemName: "1,2-Dichloroethane",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1113-02-6",
      chemName: "Omethoate",
      value: 0.4,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "114-26-1",
      chemName: "Propoxur",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 40,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "115-32-2",
      chemName: "Dicofol",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "115-90-2",
      chemName: "Fensulfothion",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1194-65-6",
      chemName: "Dichlobenil",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "121-75-5",
      chemName: "Maldison",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "122-39-4",
      chemName: "DPA",
      value: 500,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "127-18-4",
      chemName: "Tetrachloroethene",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "13121-70-5",
      chemName: "Cyhexatin",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "13194-48-4",
      chemName: "Ethoprophos",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1332-21-4",
      chemName: "Asbestos",
      value: 0,
      units: "-",
      comments: "No guideline recommended at this time",
    },
    {
      chemCode: "13457-18-6",
      chemName: "Pyrazophos",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "142-59-6",
      chemName: "Nabam",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "145-73-3",
      chemName: "Endothal",
      value: 600,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "14797-55-8(as N)",
      chemName: "Nitrate-N",
      value: 10000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "14797-65-0(as N)",
      chemName: "Nitrite-N",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "14808-79-8",
      chemName: "Sulfate",
      value: 400000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 500,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "15972-60-8",
      chemName: "Alachlor",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "16605-91-7",
      chemName: "Polychlorinated biphenyls",
      value: 0.1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "16887-00-6",
      chemName: "Chloride",
      value: 400000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1689-84-5",
      chemName: "Bromoxynil",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1702-17-6",
      chemName: "3,6-Dichloropicolinic acid",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "17029-22-0",
      chemName: "Hexaflurate",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "17804-35-2",
      chemName: "Benomyl",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "18496-25-8",
      chemName: "Sulfide",
      value: 50,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "19044-88-3",
      chemName: "Oryzalin",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1918-00-9",
      chemName: "Dicamba",
      value: 300,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1918-02-1",
      chemName: "Picloram",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "1982-47-4",
      chemName: "Chloroxuron",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "21087-64-9",
      chemName: "Metribuzin",
      value: 5,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2164-17-2",
      chemName: "Fluometuron",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "23103-98-2",
      chemName: "Pirimicarb",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2312-35-8",
      chemName: "Propargite",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "23505-41-1",
      chemName: "Pirimiphos-ethyl",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "23564-06-9",
      chemName: "Thiophanate",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "25057-89-0",
      chemName: "Bentazone",
      value: 400,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2540-82-1",
      chemName: "Formothion",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2631-37-0",
      chemName: "Promecarb",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 40,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "28434-01-7",
      chemName: "Bioresmethrin",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "29232-93-7",
      chemName: "Pirimiphos-methyl",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "298-00-0",
      chemName: "Parathion-methyl",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "298-04-4",
      chemName: "Disulfoton",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "299-84-3",
      chemName: "Fenchlorphos",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "30560-19-1",
      chemName: "Acephate",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "309-00-2",
      chemName: "Aldrin",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "330-54-1",
      chemName: "Diuron",
      value: 40,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "3337-71-1",
      chemName: "Asulam",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "3383-96-8",
      chemName: "Temephos",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "35400-43-2",
      chemName: "Sulprofos",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "35554-44-0",
      chemName: "Bromazil",
      value: 600,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "37924-13-3",
      chemName: "Perfluidone",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "40487-42-1",
      chemName: "Pendimethalin",
      value: 600,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "41198-08-7",
      chemName: "Profenofos",
      value: 0.6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "4685-14-7",
      chemName: "Paraquat",
      value: 40,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "470-90-6",
      chemName: "Chlorfenvinphos",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "4726-14-1",
      chemName: "Nitralin",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "4824-78-6",
      chemName: "Bromophos-ethyl",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "49866-87-7",
      chemName: "Difenzoquat",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 0.01,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "51-03-6",
      chemName: "Piperonyl butoxide",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "51218-45-2",
      chemName: "Metolachlor",
      value: 800,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "51235-04-2",
      chemName: "Hexazinone",
      value: 600,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "51338- 27-3",
      chemName: "Diclofop-methyl",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "51630-58-1",
      chemName: "Fenvalerate",
      value: 40,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "52645-53-1",
      chemName: "Permethrin",
      value: 300,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "52-68-6",
      chemName: "Trichlorofon",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "52756-25-9",
      chemName: "Flamprop-methyl",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "55335-06-3",
      chemName: "Triclopyr",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "56-23-5",
      chemName: "Carbon tetrachloride",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "563-12-2",
      chemName: "Ethion",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "58-90-2",
      chemName: "2,3,4,6-Tetrachlorophenol",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "59682-52-9",
      chemName: "Fosamine (ammonium salt)",
      value: 3000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "60-57-1",
      chemName: "Dieldrin",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "6164-98-3",
      chemName: "Chlordimeform",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "61-82-5",
      chemName: "Amitrol",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "62-73-7",
      chemName: "Dichlorvos",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "63-25-2",
      chemName: "Carbaryl",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "640-15-3",
      chemName: "Thiometon",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "6923-22-4",
      chemName: "Monocrotophos",
      value: 2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "709-98-8",
      chemName: "Propanil",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7439-89-6",
      chemName: "Iron",
      value: 300,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 50,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 50,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-23-5",
      chemName: "Sodium",
      value: 300000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 50,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-39-3",
      chemName: "Barium",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 5,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium",
      value: 50,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 5000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "75-35-4",
      chemName: "1,1-Dichloroethene",
      value: 0.3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "759-94-4",
      chemName: "EPTC",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 3,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia (as N)",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7782-44-7",
      chemName: "Oxygen",
      value: 6.5,
      units: "ug/L",
      comments: ">80% saturation (6.5), < 100% n(9.1)",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "7786-34-7",
      chemName: "Mevinphos",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "786-19-6",
      chemName: "Carbophenothion",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "79-01-6",
      chemName: "Trichloroethene",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "8065-48-3",
      chemName: "Demeton",
      value: 30,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "82-68-8",
      chemName: "Quintozene",
      value: 6,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos-methyl",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-Trichlorophenol",
      value: 10,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "93-72-1",
      chemName: "Fenoprop",
      value: 20,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 100,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "950-37-8",
      chemName: "Methidathion",
      value: 60,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "95-95-4",
      chemName: "2,4,5-Trichlorophenol",
      value: 1,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "Clopzralid",
      chemName: "Clopzralid",
      value: 1000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "Gross_alpha_activity",
      chemName: "Gross alpha activity",
      value: 0.1,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Gross_beta_activity",
      chemName: "Gross beta activity (excluding activity of 40K)",
      value: 0.1,
      units: "Bq/L",
      comments: "",
    },
    {
      chemCode: "Hardness_as_CaCO3",
      chemName: "Hardness (as CaCO3)",
      value: 500000,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "Organics (CCE & CAE)",
      chemName: "Organics (CCE & CAE)",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "pH_Field",
      chemName: "pH",
      value: {
        min: 6.5,
        max: 8.5,
      },
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "pH_Lab",
      chemName: "pH",
      value: {
        min: 6.5,
        max: 8.5,
      },
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "Phenolics",
      chemName: "Phenolics",
      value: 2,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "Surfactant",
      chemName: "Surfactant (MBAS)",
      value: 200,
      units: "ug/L",
      comments: "",
    },
    {
      chemCode: "TDS",
      chemName: "Total dissolved solids",
      value: 1000000,
      units: "ug/L",
      comments: "",
    },
  ],
};
