import { Standard } from "../../standardsTypes";

export const ANZECC_2000_slightly_moderately_disturbed_systems: Standard = {
  standardInfo: {
    matrix: "Water",
    leached: false,
  },
  visual: {
    colour: "#AEB6BF",
    name: "ANZECC 2000 Slightly to Moderately Disturbed Systems",
    whiteBar: "ANZECC 2000 Water Quality Guidelines",
    rowB: "Slightly to Moderately Disturbed Systems",
  },
  values: [
    {
      chemCode: "106-42-3",
      chemName: "p-xylene",
      value: 200,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "106-46-7",
      chemName: "1,4-dichlorobenzene",
      value: 60,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "106-48-9",
      chemName: "4-chlorophenol",
      value: 220,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "1071-83-6",
      chemName: "Glyphosate",
      value: 370,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "108-95-2",
      chemName: "Phenol",
      value: 320,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "11097-69-1",
      chemName: "Aroclor 1254",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "115-29-7",
      chemName: "Endosulfan",
      value: 0.03,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "118-96-7",
      chemName: "2,4,6-trinitrotoluene",
      value: 140,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "120-82-1",
      chemName: "1,2,4-trichlorobenzene",
      value: 85,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "120-83-2",
      chemName: "2,4-dichlorophenol",
      value: 120,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "121-14-2",
      chemName: "2,4-dinitrotoluene",
      value: 16,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "121-75-5",
      chemName: "Malathion",
      value: 0.05,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "122-14-5",
      chemName: "Fenitrothion",
      value: 0.2,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "122-34-9",
      chemName: "Simazine",
      value: 3.2,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "131-11-3",
      chemName: "Dimethylphthalate",
      value: 3700,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "137-26-8",
      chemName: "Thiram",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "14797-55-8",
      chemName: "Nitrate",
      value: 700,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "14797-55-8(as N)",
      chemName: "Nitrate as N",
      value: 158.1,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "1563-66-2",
      chemName: "Carbofuran",
      value: 0.06,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "1582-09-8",
      chemName: "Trifluralin",
      value: 2.6,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "16752-77-5",
      chemName: "Methomyl",
      value: 3.5,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "18540-29-9",
      chemName: "Chromium (CrVI)",
      value: 1,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "1912-24-9",
      chemName: "Atrazine",
      value: 13,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "2212-67-1",
      chemName: "Molinate",
      value: 3.4,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "22569-72-8",
      chemName: "Arsenic (As III)",
      value: 24,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "28249-77-6",
      chemName: "Thiobencarb",
      value: 2.8,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "2921-88-2",
      chemName: "Chlorpyrifos",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "333-41-5",
      chemName: "Diazinon",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "34014-18-1",
      chemName: "Tebuthiuron",
      value: 2.2,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "DDT",
      value: 0.006,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "51-28-5",
      chemName: "2,4-dinitrophenol",
      value: 45,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "53469-21-9",
      chemName: "Aroclor 1242",
      value: 0.3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "541-73-1",
      chemName: "1,3-dichlorobenzene",
      value: 260,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "554-00-7",
      chemName: "2,4-dichloroaniline",
      value: 7,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "56-38-2",
      chemName: "Parathion",
      value: 0.004,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "57-12-5",
      chemName: "Cyanide",
      value: 7,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.03,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 0.2,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "58-90-2",
      chemName: "2,3,4,6- tetrachlorophenol",
      value: 10,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "60-51-5",
      chemName: "Dimethoate",
      value: 0.15,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "62-53-3",
      chemName: "Aniline",
      value: 8,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "64-17-5",
      chemName: "Ethanol",
      value: 1400,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "66230-04-4",
      chemName: "Esfenvalerate",
      value: 0.001,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "67-72-1",
      chemName: "Hexachloroethane",
      value: 290,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "71-43-2",
      chemName: "Benzene",
      value: 950,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7429-90-5",
      chemName: "Aluminium",
      value: 55,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 3.4,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7439-96-5",
      chemName: "Manganese",
      value: 1900,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury (inorganic)",
      value: 0.06,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 11,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 0.05,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-38-2 V",
      chemName: "Arsenic (AsV)",
      value: 13,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-42-8",
      chemName: "Boron",
      value: 370,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 0.2,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 1.4,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 8,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "76-44-8",
      chemName: "Heptachlor",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7664-41-7",
      chemName: "Ammonia",
      value: 900,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7664-41-7 (as N)",
      chemName: "Ammonia as N",
      value: 698.8,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7782-49-2",
      chemName: "Selenium (Total)",
      value: 5,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7782-50-5_Total",
      chemName: "Chlorine",
      value: 3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "7783-06-4",
      chemName: "Hydrogen sulfide",
      value: 1,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "79-00-5",
      chemName: "1,1,2-trichloroethane",
      value: 6500,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "8001-35-2",
      chemName: "Toxaphene",
      value: 0.1,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "84-66-2",
      chemName: "Diethylphthalate",
      value: 1000,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "84-74-2",
      chemName: "Dibutylphthalate",
      value: 9.9,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "85-00-7",
      chemName: "Diquat",
      value: 1.4,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "86-50-0",
      chemName: "Azinphos methyl",
      value: 0.01,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "87-61-6",
      chemName: "1,2,3-trichlorobenzene",
      value: 3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "87-86-5",
      chemName: "Pentachlorophenol",
      value: 3.6,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "88-06-2",
      chemName: "2,4,6-trichlorophenol",
      value: 3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "9003-56-9",
      chemName: "Poly(acrylonitrile-co-butadiene-co-styrene)",
      value: 530,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 16,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 16,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "93-76-5",
      chemName: "2,4,5-T",
      value: 36,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "94-75-7",
      chemName: "2,4-D",
      value: 280,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "95-47-6",
      chemName: "o-xylene",
      value: 350,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "95-50-1",
      chemName: "1,2-dichlorobenzene",
      value: 160,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "95-57-8",
      chemName: "2-chlorophenol",
      value: 340,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "95-76-1",
      chemName: "3,4-dichloroaniline",
      value: 3,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "98-95-3",
      chemName: "Nitrobenzene",
      value: 550,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "AES",
      chemName: "Alcohol ethoxyolated sulfate (AES)",
      value: 650,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "AESurfactant",
      chemName: "Alcohol ethoxylated surfactants",
      value: 140,
      units: "ug/l",
      comments: "",
    },
    {
      chemCode: "LAS",
      chemName: "Linear alkylbenzene sulfonates",
      value: 280,
      units: "ug/l",
      comments: "",
    },
  ],
};
