import { Standard } from "../../standardsTypes";

export const ANZECC_2000_Sediment_ISGC_High: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  visual: {
    colour: "#D6DBDF",
    name: "ANZECC 2000 Sediment ISGC-High",
  },
  values: [
    {
      chemCode: "120-12-7",
      chemName: "Anthracene",
      value: 1100,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "129-00-0",
      chemName: "Pyrene",
      value: 2600,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "206-44-0",
      chemName: "Fluoranthene",
      value: 5100,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "208-96-8",
      chemName: "Acenaphthalene",
      value: 640,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "218-01-9",
      chemName: "Chrysene",
      value: 2800,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "3547-04-4",
      chemName: "p.p'-DDE",
      value: 27,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "Total DDT",
      value: 46,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 1600,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "53-19-0 + 72-54-8",
      chemName: "o,p'- + p.p'-DDD",
      value: 20,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "53-70-3",
      chemName: "Dibenzo(a,h)anthrancene",
      value: 260,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "56-55-3",
      chemName: "Benzo(a)anthracene",
      value: 1600,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 6,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 1,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "60-57-1",
      chemName: "Dieldrin",
      value: 8,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "688-73-3",
      chemName: "Tributyltin",
      value: 70,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 8,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 220,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 52,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 3.7,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-36-0",
      chemName: "Antimony",
      value: 25,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 70,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 10,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium",
      value: 370,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 270,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 410,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "83-32-9",
      chemName: "Acenaphthene",
      value: 500,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "85-01-8",
      chemName: "Phenanthrene",
      value: 1500,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "86-73-7",
      chemName: "Fluorene",
      value: 540,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 2100,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 2100,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "PAH_HEAVY",
      chemName: "High Molecular Weight PAHs c",
      value: 9600,
      units: "ug/kg",
      comments:
        "High molceular weight PAHs are the sum of concentrations of benzo(a)anthracene, benzo(a)pyrene, chrysene, dibenzo(a,h)anthracene, fluoranthene and pyrene.",
    },
    {
      chemCode: "PAH_LIGHT",
      chemName: "Low Molecular Weight PAHS c",
      value: 3160,
      units: "ug/kg",
      comments:
        "Low molecular weight PAHs are the sum of concentrations of acenaphthene, acenaphthalene, anthracene, fluorene, 2-methylnaphthalene, naphthalene and phenanthrene",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Total PAHs",
      value: 45000,
      units: "ug/kg",
      comments: "",
    },
  ],
};
