import { Standard } from "../../standardsTypes";

export const ANZECC_2000_Sediment_ISGC_Low: Standard = {
  standardInfo: {
    matrix: "Soil",
    leached: false,
  },
  values: [
    {
      chemCode: "120-12-7",
      chemName: "Anthracene",
      value: 85,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "129-00-0",
      chemName: "Pyrene",
      value: 665,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "1336-36-3",
      chemName: "Total PCBs",
      value: 23,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "206-44-0",
      chemName: "Fluoranthene",
      value: 600,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "208-96-8",
      chemName: "Acenaphthalene",
      value: 44,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "218-01-9",
      chemName: "Chrysene",
      value: 384,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "3547-04-4",
      chemName: "p.p'-DDE",
      value: 2.2,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "50-29-3",
      chemName: "Total DDT",
      value: 1.6,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "50-32-8",
      chemName: "Benzo(a)pyrene",
      value: 430,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "53-19-0 + 72-54-8",
      chemName: "o,p'- + p.p'-DDD",
      value: 2,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "53-70-3",
      chemName: "Dibenzo(a,h)anthrancene",
      value: 63,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "56-55-3",
      chemName: "Benzo(a)anthracene",
      value: 261,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "57-74-9",
      chemName: "Chlordane",
      value: 0.5,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "58-89-9",
      chemName: "Lindane",
      value: 0.32,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "60-57-1",
      chemName: "Dieldrin",
      value: 0.02,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "688-73-3",
      chemName: "Tributyltin",
      value: 5,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "72-20-8",
      chemName: "Endrin",
      value: 0.02,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "7439-92-1",
      chemName: "Lead",
      value: 50,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7439-97-6",
      chemName: "Mercury",
      value: 0.15,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-02-0",
      chemName: "Nickel",
      value: 21,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-22-4",
      chemName: "Silver",
      value: 1,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-36-0",
      chemName: "Antimony",
      value: 2,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-38-2",
      chemName: "Arsenic",
      value: 20,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-43-9",
      chemName: "Cadmium",
      value: 1.5,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-47-3",
      chemName: "Chromium",
      value: 80,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-50-8",
      chemName: "Copper",
      value: 65,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "7440-66-6",
      chemName: "Zinc",
      value: 200,
      units: "mg/kg",
      comments: "",
    },
    {
      chemCode: "83-32-9",
      chemName: "Acenaphthene",
      value: 16,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "85-01-8",
      chemName: "Phenanthrene",
      value: 240,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "86-73-7",
      chemName: "Fluorene",
      value: 19,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "91-20-3",
      chemName: "Naphthalene",
      value: 160,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "91-20-3_VOC",
      chemName: "Naphthalene",
      value: 160,
      units: "ug/kg",
      comments: "",
    },
    {
      chemCode: "PAH_HEAVY",
      chemName: "High Molecular Weight PAHs c",
      value: 1700,
      units: "ug/kg",
      comments:
        "High molceular weight PAHs are the sum of concentrations of benzo(a)anthracene, benzo(a)pyrene, chrysene, dibenzo(a,h)anthracene, fluoranthene and pyrene.",
    },
    {
      chemCode: "PAH_LIGHT",
      chemName: "Low Molecular Weight PAHS c",
      value: 552,
      units: "ug/kg",
      comments:
        "Low molecular weight PAHs are the sum of concentrations of acenaphthene, acenaphthalene, anthracene, fluorene, 2-methylnaphthalene, naphthalene and phenanthrene",
    },
    {
      chemCode: "TOTALPAH",
      chemName: "Total PAHs",
      value: 4000,
      units: "ug/kg",
      comments: "",
    },
  ],
};
